name: 'PR Trivia Checker'
description: 'Bloquea Pull Requests hasta que el autor complete una trivia de validación externa'
author: 'Your Name'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  api-key:
    description: 'API Key de autenticación proporcionada por el servicio de trivia'
    required: true
  github-token:
    description: 'Token de GitHub para crear comentarios (usa secrets.GITHUB_TOKEN)'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
